stages:
  - test
  - build
  - deploy

test_job:
  stage: test
  image: php:8.2-cli
  script:
    - php tests/search_test.php

build_job:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t gitlab-cicd-demo --build-arg CI_PROVIDER=GitLab .
    - docker save gitlab-cicd-demo | gzip > gitlab-image.tar.gz
  artifacts:
    paths:
      - gitlab-image.tar.gz
  needs: [test_job]

simulate_deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "🚀 Starting deployment simulation…"
    - echo " • Подключаемся к серверу…"
    - sleep 1
    - echo " • Копируем файлы…"
    - sleep 1
    - echo " • Перезапускаем сервисы…"
    - sleep 1
    - echo "✅ Deployment simulation completed!"
  when: manual     # можно запускать вручную из интерфейса
  only:
    - main
