name: GitHub CI/CD Web Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/upload-artifact@v3.1.2

      - name: Build Docker image
        run: docker build -t github-cicd-web-demo --build-arg CI_PROVIDER=GitHub .

      - name: Save image to artifact
        run: docker save github-cicd-web-demo | gzip > image.tar.gz

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar.gz

